config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms
  post 'pick_card', to: 'cards#pick_card'
  post 'shuffle_card', to: 'cards#shuffle_card'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  # Association
  belongs_to :set_card

  # Mount uploader
  mount_uploader :image, ImageUploader
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :set_card, optional: true
end

app/models/set_card.rb
class SetCard < ApplicationRecord
  # Association
  has_many :cards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def shuffle_card
    set = SetCard.find(params[:set_id])
    cards = set.cards.shuffle
    room = Room.find(params[:room_id])
    room.update(
      set_card_id: set.id,
      card_ids: [],
      list_cards: cards.pluck(:id)
    )

    ActionCable.server.broadcast("rooms:room_#{ room.id }", { set_id: set.id, cards: cards, shuffle: true })
    render json: {}
  end

  def pick_card
    room = Room.find(params[:room_id])
    room.card_ids << params[:card_id]
    room.save

    ActionCable.server.broadcast("rooms:room_#{ room.id }", { card_id: params[:card_id], shuffle: false })
    render json: {}
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])

    @cards = if @room.set_card.present? && !@room.list_cards.empty?
      Card.find(@room.list_cards).sort_by{ |card| @room.list_cards.index card.id }
    end

    @sets = SetCard.all
  end

  def leave_room
    session[:room_id] = nil
    redirect_to rooms_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickCard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<ul>
  <% @rooms.each do |room| %>
    <li>
      <%= link_to room.name, room_path(room) %>
    </li>
  <% end %>
</ul>

app/views/rooms/show.html.erb
<div id='shuffle-card'>
  <div onclick="shuffleCard(<%= @room.set_card&.id %>)" style='color: lightblue; cursor: pointer;'>
    Shuffle card
  </div>
</div>

<br/>

<div>
  <%= select_tag :tenant_id, options_for_select(@sets.collect { |set| [set.title, set.id] }, selected: @room.set_card&.id), { onchange: "shuffleCard(this.value)", include_blank: true } %>
</div>

<div class="list-card">
  <% @cards&.each_with_index do |card, index| %>
    <div class="card-wrapper flip-right <%= 'active' if @room.card_ids.include?(card.id.to_s) %>" id="<%= card.id %>">
      <div class="card">
        <div class="front" onclick="<%= 'clickCard(this)' if !@room.card_ids.include?(card.id.to_s) %>"><%= index + 1 %></div>
        <div class="back">
          <%= image_tag card.image.thumb.url %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  function clickCard(el) {
    var id = $(el).parent().parent().attr('id')
    $.ajax({
      url: '/pick_card',
      type: 'POST',
      data: {
        room_id: <%= @room.id %>,
        card_id: id
      }
    });
  }

  function shuffleCard(id) {
    if (id) {
      $.ajax({
        url: '/shuffle_card',
        type: 'POST',
        data: {
          room_id: <%= @room.id %>,
          set_id: id
        }
      });
    }
  }
</script>